# --- Project Metadata ---
SAMPLES: ["SRR1805151"]

# --- Subsampling Parameters ---
FRACTIONS: ["0.10", "0.25", "0.50", "0.75", "0.90", "1.00"]

# --- Path Configuration ---
RAW_DATA_DIR: "data/raw/"
KRAKEN_DB: "database/kraken2_std8"

# --- Tool Parameters ---
TAX_LEVEL: "S"

SEED: 111

